(cl:defpackage apriltags2_ros-msg
  (:use )
  (:export
   "<APRILTAGDETECTION>"
   "APRILTAGDETECTION"
   "<APRILTAGDETECTION>"
   "APRILTAGDETECTION"
   "<APRILTAGDETECTIONARRAY>"
   "APRILTAGDETECTIONARRAY"
   "<APRILTAGDETECTIONARRAY>"
   "APRILTAGDETECTIONARRAY"
  ))

